// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLKXSXScf6ylpKrjAaahVN3icK50vqZw',
    appId: '1:74197607594:android:f719ddef283a65c8be9cd3',
    messagingSenderId: '74197607594',
    projectId: 'test-aula29-04',
    storageBucket: 'test-aula29-04.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp7XHe6C4SOoAUmIGt2zmao9CgQkCHTvY',
    appId: '1:74197607594:web:97fd2ed737a9de61be9cd3',
    messagingSenderId: '74197607594',
    projectId: 'test-aula29-04',
    authDomain: 'test-aula29-04.firebaseapp.com',
    storageBucket: 'test-aula29-04.firebasestorage.app',
    measurementId: 'G-5H3L1RJ6MG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHTSk-VxBbOqlaQohYo8ukFtdmRmtJsA',
    appId: '1:74197607594:ios:6beac2e87403b143be9cd3',
    messagingSenderId: '74197607594',
    projectId: 'test-aula29-04',
    storageBucket: 'test-aula29-04.firebasestorage.app',
    iosBundleId: 'com.example.aulaFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHTSk-VxBbOqlaQohYo8ukFtdmRmtJsA',
    appId: '1:74197607594:ios:6beac2e87403b143be9cd3',
    messagingSenderId: '74197607594',
    projectId: 'test-aula29-04',
    storageBucket: 'test-aula29-04.firebasestorage.app',
    iosBundleId: 'com.example.aulaFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp7XHe6C4SOoAUmIGt2zmao9CgQkCHTvY',
    appId: '1:74197607594:web:d9fa942347818d8ebe9cd3',
    messagingSenderId: '74197607594',
    projectId: 'test-aula29-04',
    authDomain: 'test-aula29-04.firebaseapp.com',
    storageBucket: 'test-aula29-04.firebasestorage.app',
    measurementId: 'G-TS9WGEL40L',
  );

}